[package]
name = "tor-dirserver"
version = "0.33.0"
authors = ["The Tor Project, Inc.", "Clara Engler <cve@torproject.org>"]
edition = "2021"
rust-version = "1.83"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Implements dirserver functionality"
keywords = ["tor", "arti"]
# We must put *something* here and this will do
categories = ["rust-patterns"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
thiserror = "2.0.16"
