#!/usr/bin/env bash
#
# Run `cargo test` for every crate with the default features

set -euo pipefail

: "${CARGO:=cargo}"

x () {
    echo ": $*"
    "$@"
}

export -f x

test_crate () {
    echo ==================== "$1" ====================
    x cargo test -p "$1" --all-targets 
}

export -f test_crate

./maint/list_crates --all | parallel --jobs "$1" -N1 -m test_crate
